apiVersion: v1
kind: Pod
metadata:
  name: trend-server
  namespace: bitly
  labels:
    name: trend-server
spec:
  containers:
  - name: trend-server
    image: gcr.io/cmpe281-267121/trend-server
    env:
    - name: RABBITMQ_SERVER
      value: "rabbitmq.us-central1-f.c.cmpe281-267121.internal"
    - name: RABBITMQ_USER
      value: "user"
    - name: RABBITMQ_PASSWORD
      value: "password"
    - name: MONGODB_SERVER
      value: "mongodb-ts.us-central1-b.c.cmpe281-267121.internal"
    - name: MONGODB_USER
      value: "cmpe281"
    - name: MONGODB_PASSWORD
      value: "mymongotspassword"
    imagePullPolicy: Always
    ports:
    - containerPort: 3002
      name: http
      protocol: TCP
