apiVersion: v1
kind: Pod
metadata:
  name: control-panel
  namespace: bitly
  labels:
    name: control-panel
spec:
  containers:
  - name: control-panel
    image: gcr.io/cmpe281-267121/control-panel
    env:
    - name: RABBITMQ_SERVER
      value: "rabbitmq.us-central1-f.c.cmpe281-267121.internal"
    - name: MONGODB_SERVER
      value: "mongodb-cp.us-central1-a.c.cmpe281-267121.internal"
    - name: MONGODB_USER
      value: "cmpe281"
    - name: MONGODB_PASSWORD
      value: "mymongocppassword"
    - name: RABBITMQ_USER
      value: user
    - name: RABBITMQ_PASSWORD
      value: password
    ports:
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
